# Generated by Django 3.1.13 on 2024-11-23 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='StudentRegister',
        ),
    ]
